name: Build and Run Integration Tests.

on:
  pull_request:
    branches: [ "**" ]
  push: 
    branches: ["master"]

jobs:
  docker-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Cache all docker images in docker-compose.yml
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('docker-compose.yml') }}
      
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
